language: cpp
sudo: false
os: linux
dist: trusty
cache:
    apt: true

apt:
    matrix:
        - sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
        - sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

env:
    - BUILD_NAME="build1" THREAD="x"
    - BUILD_NAME="build2" THREAD="y"

before_install: echo "==== before install ${BUILD_NAME}"
install:        echo "====        install ${BUILD_NAME}"

before_script: echo  "==== before script ${BUILD_NAME}"
script: ./build.sh

