language: cpp
sudo: false
os: linux
dist: trusty
cache:
    apt: true

# By default use gcc5 for building the test suite.
# Additional targets are added to test other compilers below.
addons:
    apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - g++-5
           - mpich
           - libmpich-dev

#env:
#   - BUILD_NAME=alpha THREAD=1 MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
#   - BUILD_NAME=gamma THREAD=3 MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

matrix:
    include:
    ################### GCC 6
      env:
        - BUILD_NAME=build1 THREAD=x
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - echo "==== before install ${BUILD_NAME}"
  # Travis sets CC and CXX after the "env" variables are set, and before the
  # before_install step.
  - eval "${MATRIX_EVAL}"

install:
  - echo "====        install ${BUILD_NAME}"

before_script:
    - echo  "==== before script ${BUILD_NAME}"

script: ./build.sh

notifications:
    email: false
