language: cpp
sudo: false
os: linux
dist: trusty
cache:
    apt: true

# There is no concise way to build a matrix with different compiler versions
# So take the manual approach of using include to explicitly create each case

addons:
    - apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - g++-5
    - apt:
        sources:
           - ubuntu-toolchain-r-test
        packages:
           - g++-7

env:
    - BUILD_NAME=alpha THREAD=1 MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - BUILD_NAME=beta  THREAD=2 MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - BUILD_NAME=gamma THREAD=3 MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

matrix:
    include:
    #-------------------
    # GCC 6
    #-------------------
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BUILD_NAME=build1 THREAD=x
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BUILD_NAME=build2 THREAD=y
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - echo "==== before install ${BUILD_NAME}"
  - eval "${MATRIX_EVAL}"

install:
  - echo "====        install ${BUILD_NAME}"

before_script:
    - echo  "==== before script ${BUILD_NAME}"

script: ./build.sh

notifications:
    email: false
