language: cpp
sudo: false
os: linux
dist: trusty
cache:
    apt: true

# There is no concise way to build a matrix with different compiler versions
# So take the manual approach of using include to explicitly create each case

matrix:
    include:
    #-------------------
    # GCC 6
    #-------------------
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BUILD_NAME=build1 THREAD=x
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BUILD_NAME=build2 THREAD=y
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - echo "==== before install ${BUILD_NAME}"
  - eval "${MATRIX_EVAL}"

install:
  - echo "====        install ${BUILD_NAME}"

before_script:
    - echo  "==== before script ${BUILD_NAME}"

script: ./build.sh

