language: cpp
sudo: false
os: linux
dist: trusty
cache:
    apt: true

apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-5

env:
    - BUILD_NAME="build1" THREAD="x"
    - BUILD_NAME="build2" THREAD="y"

matrix:
    include:
        - 


before_install: echo ${BUILD_NAME}
install: echo ${BUILD_NAME}

before_script: echo "==== before script"
script: ./build.sh

